Repository maxwroc/battery-state-card, pull requests merged in 2022-01, with the labels that each got.

#368 Support for charging indicator/value stored in object
  README.md
  src/custom-elements/battery-state-entity.ts
  test/entity/icon.test.ts
  test/entity/secondary-info.test.ts
  test/entity/state.test.ts
  test/helpers.ts
Labels: enhancement

#369 Dynamic values in secondary_info (other entity states/attributes etc)
  .github/workflows/continous-integration.yml
  README.md
  package.json
  src/custom-elements/battery-state-entity.ts
  src/rich-string-processor.ts
  src/typings.d.ts
  test/card/entity-list.test.ts
  test/entity/icon.test.ts
  test/entity/name.test.ts
  test/entity/secondary-info.test.ts
  test/entity/state.test.ts
  test/helpers.ts
  test/other/rich-string-processor.test.ts
Labels: enhancement

#371 Multiple levels of sorting
  .gitignore
  README.md
  package.json
  src/battery-provider.ts
  src/custom-elements/battery-state-card.ts
  src/sorting.ts
  src/typings.d.ts
  src/utils.ts
  test/helpers.ts
  test/other/sorting.test.ts
Labels: enhancement

#372 VSCode config
  .gitignore
  .vscode/launch.json
  package.json
Labels: miscellaneous

#374 Combined color settings
  README.md
  src/battery-provider.ts
  src/colors.ts
  src/custom-elements/battery-state-entity.ts
  src/typings.d.ts
  src/utils.ts
  test/other/colors.test.ts
Labels: enhancement

#383 Don't prioritize higher battery_level attribute (over the state) if its value is not a number
  src/custom-elements/battery-state-entity.ts
  src/utils.ts
Labels: bug

#386 State source priority tests
  package.json
  test/entity/state.test.ts
  test/helpers.ts
Labels: miscellaneous
