Repository maxwroc/battery-state-card, pull requests merged in 2024-02, with the labels that each got.

#672 Fixed HA formatted state parsing
  package.json
  src/entity-fields/battery-level.ts
  test/other/entity-fields/battery-level.test.ts
Labels: bug

#678 Sort by numeric state (not displayed value)
  src/custom-elements/battery-state-entity.ts
  src/sorting.ts
  test/card/sorting.test.ts
Labels: bug

#681 Fix capitalizing name when it is an empty string
  src/entity-fields/get-name.ts
  test/other/entity-fields/get-name.test.ts
Labels: bug

#671 Extended entity data like area or device
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  package.json
  src/battery-provider.ts
  src/custom-elements/battery-state-entity.css
  src/custom-elements/battery-state-entity.ts
  src/custom-elements/battery-state-entity.views.ts
  src/custom-elements/lovelace-card.ts
  src/entity-fields/battery-level.ts
  src/entity-fields/get-icon.ts
  src/entity-fields/get-name.ts
  src/entity-fields/get-secondary-info.ts
  src/rich-string-processor.ts
  src/type-extensions.ts
  src/typings.d.ts
  test/other/entity-fields/battery-level.test.ts
  test/other/entity-fields/get-name.test.ts
  test/other/entity-fields/get-secondary-info.test.ts
  test/other/filter.test.ts
  test/other/rich-string-processor.test.ts
Labels: enhancement

#682 Processing exclude filter after entity update
  src/battery-provider.ts
  src/custom-elements/battery-state-entity.ts
Labels: enhancement

#683 Allow filtering by extended entity data
  src/filter.ts
  src/utils.ts
  test/other/filter.test.ts
Labels: enhancement

#685 Don't render anything if the value was not found in KString
  src/rich-string-processor.ts
  test/other/entity-fields/get-secondary-info.test.ts
Labels: enhancement

#686 Respect HomeAssistant entity visibility setting
  src/battery-provider.ts
  src/type-extensions.ts
  test/card/filters.test.ts
  test/helpers.ts
Labels: enhancement

#692 Fix typos in README (Common options)
  README.md
Labels: miscellaneous

#689 Search for all reported exceptions - not only open ones
  src/custom-elements/lovelace-card.ts
Labels: miscellaneous

#693 Update README.md
  README.md
Labels: miscellaneous

#699 Fix exception when entity attributes are missing
  package.json
  src/entity-fields/battery-level.ts
  src/entity-fields/get-name.ts
  test/helpers.ts
  test/other/entity-fields/battery-level.test.ts
  test/other/entity-fields/get-name.test.ts
Labels: bug

#700 Fixed filtering by the exact value type
  src/filter.ts
  src/typings.d.ts
  src/utils.ts
  test/other/filter.test.ts
Labels: bug

#701 Entity not available warning
  src/custom-elements/battery-state-entity.ts
  src/entity-fields/battery-level.ts
  src/entity-fields/charging-state.ts
  src/entity-fields/get-icon.ts
  src/entity-fields/get-name.ts
  src/entity-fields/get-secondary-info.ts
  src/rich-string-processor.ts
  test/card/entity-list.test.ts
  test/helpers.ts
  test/other/entity-fields/battery-level.test.ts
  test/other/entity-fields/charging-state.test.ts
  test/other/entity-fields/get-icon.test.ts
  test/other/entity-fields/get-name.test.ts
Labels: enhancement

#707 Removed restrictions for color thresholds
  src/colors.ts
  src/typings.d.ts
  test/other/colors.test.ts
Labels: enhancement
